version: "3.9"

services:
  rust_web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust-web_container
    env_file:
      - envs/database.env
      - envs/jenkins.env
      - envs/openai.env
    networks:
      nginx-network:
        ipv4_address: 172.30.0.81

networks:
  nginx-network:
    external: true
    name: nginx-net
    ipam:
      driver: bridge
      config:
        - subnet: 172.30.0.1/16

